apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  AZURE_AKS_IDENTITY_CLIENT_ID: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
  AZURE_OPENAI_ENDPOINT: {{.Env.AZURE_OPENAI_ENDPOINT}}
  AZURE_OPENAI_API_VERSION: {{.Env.AZURE_OPENAI_API_VERSION}}
  AZURE_OPENAI_DEPLOYMENT_NAME: {{.Env.AZURE_OPENAI_DEPLOYMENT_NAME}}
  BING_SEARCH_ENDPOINT: {{.Env.BING_SEARCH_ENDPOINT}}
  BING_SEARCH_KEY: {{.Env.BING_SEARCH_KEY}}

