name: Validate AZD template
on:
  push:
    branches: [ aca-openai-agent ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ main ]
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Upgrade bicep
        run: |
          which bicep
          sudo curl -o $(which bicep) -L https://github.com/Azure/bicep/releases/download/v0.31.92/bicep-linux-x64
          sudo chmod +x $(which bicep)

      - name: Build Bicep for linting
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
        with:
          inlineScript: bicep build -f infra/main.bicep --stdout

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.Azure
          baseline: Azure.Pillar.Security
          inputPath: infra/*.test.bicep
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true
        continue-on-error: true
          
        env:
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION: 'true'
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION_TIMEOUT: '30'

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2.28.1
        if: github.repository == 'Azure-Samples/contoso-creative-writer'
        with:
          sarif_file: reports/ps-rule-results.sarif
